version: '3.7'
services:
    landing_app:
        build:
            context: .
        volumes:
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
            - ./cache/node_modules:/usr/share/nginx/cache/node_modules
        restart: always
        networks:
            - core-network
networks:
    core-network:
        external: true
